nats:
  tls:
    secret:
      name: nats-client-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
    verifyAndMap: true
  jetstream:
    enabled: true
    domain: hub
  
auth:
  enabled: true
  basic:
    accounts:
      # Hub Account
      form3:
        jetstream: true
        users:
        - user: form3.form3.tech
        exports:
          - service: $JS.hub.API.CONSUMER.MSG.NEXT.central.dur
            response_type: stream
          - service: $JS.ACK.central.dur.>
          - service: cent.>

      # CA Account
      ca:
        jetstream: true
        users:
        - user: ca.form3.tech
        imports:
        - service:
            account: form3
            subject: $JS.hub.API.CONSUMER.MSG.NEXT.central.dur
          to: JS.form3.API.CONSUMER.MSG.NEXT.central.dur
        - service:
            account: form3
            subject: $JS.ACK.central.dur.>
        - service:
            account: form3
            subject: cent.>

      # SYS Account
      SYS:
        users:
          - user: systemaccount@form3.tech
  systemAccount: SYS


cluster:
  enabled: true
  replicas: 3
  tls:
    secret:
      name: nats-server-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"

natsbox:
  enabled: false
