apiVersion: v1
kind: Pod
metadata:
  name: nats-box-cert
  namespace: default
spec:
  containers:
  - command:
    - tail
    - -f
    - /dev/null
    env:
    - name: NATS_URL
      value: nats
    image: natsio/nats-box:0.6.0
    imagePullPolicy: IfNotPresent
    name: nats-box
    volumeMounts:
    - mountPath: /etc/nats-certs/clients/systemaccount-cert-tls
      name: systemaccount-cert-tls-volume
    - mountPath: /etc/nats-certs/clients/form3-user-cert-tls
      name: form3-user-cert-tls
  volumes:
  - name: form3-user-cert-tls
    secret:
      secretName: form3-user-cert-tls
  - name: systemaccount-cert-tls-volume
    secret:
      secretName: systemaccount-cert-tls
