nats:
  tls:
    secret:
      name: nats-client-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
    verifyAndMap: true
  jetstream:
    enabled: false
  logging:
    debug: true
    trace: true
  
auth:
  enabled: true
  basic:
    accounts:
      PAYMENTSERVICE:
        users:
          - user: paymentservice@form3.tech
        exports:
          - stream: payments.>
      SYS:
        users:
          - user: systemaccount@form3.tech
  systemAccount: SYS


cluster:
  enabled: true
  replicas: 1
  tls:
    secret:
      name: nats-server-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"

natsbox:
  enabled: false
